### ISSUE TITLE
Reference check for rule location should also include `~`

### ISSUE THREAD

**Issue by mensfeld** [MarioRuiz/slack-smart-bot#27]
Hey,

I think (may be wrong thought), that check in this line: https://github.com/MarioRuiz/slack-smart-bot/blob/master/lib/slack/smart-bot/process_first.rb#L252 should also include checking for `~`. In general you could expand the path and check if it matches your expectation.

**Comment by MarioRuiz** [comment]
It was not intended to be used ~ as config.path, but yes in case it is used then it should be included. Thanks.
